# Site Settings
title                    : "Yihong Huang"
description              : "Personal academic homepage of Yihong Huang."
repository               : "yihonghuang361-Karl/yihonghuang.github.io"

# Important for GitHub Project Pages
url                      : "https://yihonghuang361-karl.github.io"
baseurl                  : "/yihonghuang.github.io"

google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :

# SEO Related
google_site_verification :
bing_site_verification   :
baidu_site_verification  :

# Site Author
author:
  name             : "Yihong Huang"
  avatar           : "images/android-chrome-512x512.png"
  bio              : "Undergraduate student / Research Intern"
  location         : "Singapore"
  employer         :
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID"
  email            : "yihonghuang361@gmail.com"
  researchgate     :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "yihonghuang361-Karl"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  dblp             :
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
